### ISSUE TITLE
Let's start dividing up concerns?

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#2]
So I drafted the different issues we need to cover for friday, and there's actually a LOT of work. Let's put a bunch of ideas in, and hopefully get something chosen by tomorrow afternoon, and then divide up the work.

![12077016_1072798522739807_1007406286_n](https://cloud.githubusercontent.com/assets/8978063/10298557/a2c624d2-6b9d-11e5-99e9-83e2685f874e.jpg)

**Comment by dktrotti** [comment]
I've started on a storyboard here: https://www.lucidchart.com/invitations/accept/9b4b47af-f340-4d0f-95bc-20ffe03a3a5d
