### ISSUE TITLE
FriendsList doesn't quite live update

### ISSUE THREAD

**Issue by codingHappiness** [Jacobchar/CMPUT301F15T12#22]
The friendsList activity doesn't quite live update...

Deleting or adding a friend doesn't refresh the list. Adding an additional friend / deleting an additional friend does update it... but not for the last action.

Might have something to do with things happening on different threads when fillFriendsList() is called.

**Comment by DavidjRoss** [comment]
Changing things on the server is rather slow, I had to add delays to the thread removing things to ensure that the UI actually updated
