### ISSUE TITLE
Problem: Friends List adds user by their name. There are two users named "Dominic". It only adds one. 

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#23]
Is this a corner case we're not dealing w/?

**Comment by codingHappiness** [comment]
Its a result of usernames not being unique. When searching by name, we don't display all the properties of a user object (such as their email, which could differentiate them), so the retrieval of any data from the server when matching by name will only add the first instance to the friendslist.

We could alter the method to add every entry in the returned arrayList, but more practically (for our demo) we would want to use unique user names. I was expecting that when people would add their name, they would do something like "Dominic Trottier" and "Dominic Alexander".
