### ISSUE TITLE
Friends List should display something when it returns no friends

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#25]
Currently fixing app crash when friends list is empty and no friend returned from search.

**Comment by codingHappiness** [comment]
I think this is a result of the datamanager throwing an exception when no results are found, so that could be handled with a try/catch

**Comment by hessdorfer** [comment]
It is being handled with a try/catch, but the catch is just printing a stack trace, then returning null friends list up the chain until it tries to find the size of a null and crashes. I think I fixed it but can't check until the server is up again.
