### ISSUE TITLE
EVERYONE needs to fix/write tests for ALL their modules, including UI Tests!

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#26]

**Comment by dktrotti** [comment]
Done

**Comment by Benobi42** [comment]
I've written all my tests for things that don't modify the Local user or call another activity

**Comment by hessdorfer** [comment]
Done. Okay, but you should still be writing tests that can modify the local user, and tests the check that buttons correctly open new activities!
