### ISSUE TITLE
Everyone needs to update the UML based on their code

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#28]
Does someone have a student account via github? Some of us can't add any more objects (max 60 for accts that aren't student/paid), so if someone with a student acct can add a bunch of items that would be great!! Or we can split it up into two UML diagrams.

**Comment by Benobi42** [comment]
If we do split into two diagrams, we can have something connecting the two and I can patch them together in another program possibly

**Comment by dktrotti** [comment]
Done

**Comment by Benobi42** [comment]
Done

**Comment by DavidjRoss** [comment]
Done, haven't connected the new ones rhoigh
