### ISSUE TITLE
Storyboarding 

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#3]

**Comment by codingHappiness** [comment]
https://www.lucidchart.com/documents/edit/b185e79b-f931-4ba0-8b18-70081ab60af6?shared=true

**Comment by dktrotti** [comment]
Created separate storyboard document: https://www.lucidchart.com/invitations/accept/577b4fa4-87f9-4587-b3c7-61ab5f6909a4
