### ISSUE TITLE
Work on UML

### ISSUE THREAD

**Issue by hessdorfer** [Jacobchar/CMPUT301F15T12#9]
See "UML Discussion" in the Wiki. This is due next Monday, Oct 26th.

**Comment by dktrotti** [comment]
Should we agree on a meeting time for next week to work on this? (Hopefully sometime earlier in the week)

**Comment by DavidjRoss** [comment]
I have a lab on tuesday, but am good to meet Monday or Wednesday before the 301 lab.

**Comment by codingHappiness** [comment]
I think Monday afternoon is our best bet for everyone according the schedule of availability.

**Comment by hessdorfer** [comment]
We could also split in two groups and have 1/2 work on it monday at 2 and half work on it tuesday at 2 (i'm free both days) - it might be easier to work on something like UML in smaller groups?
